name: Comment on Issues and Pull Requests

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  comment_on_issues_and_prs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Comment on issue or pull request
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Thanks for opening this issue/pull request! We'll take a look as soon as possible.