name: Comment on New Issues

on:
  issues:
    types: [opened]

jobs:
  comment_on_new_issues:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Comment on new issue
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Thanks for opening this issue! We'll take a look as soon as possible.