name: PHP Code Quality Check

on:
  push:
    branches: [ main ]

jobs:
  php-code-quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
          composer install

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs

      - name: Run PHPMD
        run: |
          phpmd src/ text phpmd.xml